name: Run Telegram Bot Daily

# Trigger the workflow every day at midnight UTC
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows you to run manually as well

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
          TOPIC_ID: ${{ secrets.TOPIC_ID }}
        run: |
          python bot.py
